borisdayma/dalle-mini

- data/CC3M_downloader.py
This script will help to scrap through the `.tsv` files and download the images from particular image links.
It does it in a multi-processing way, so using TPU, it takes only 1-1.5hrs to download all the images!
> Added CC3M data downloader script

- seq2seq/run_seq2seq_flax.py
> feat: gradient accumulation

- requirements.txt
- seq2seq/run_seq2seq_flax.py
add ability to log model by setting `--log_model`
> feat: log model

- seq2seq/run_seq2seq_flax.py
fix model config with bos and eos
> fix: model config

- seq2seq/run_seq2seq_flax.py
There is a problem with the `x` axis, see for example https://wandb.ai/wandb/hf-flax-dalle-mini/runs/b91na6ea
> Add eval_interval to evaluate and log every so often.

- seq2seq/do_big_run.sh
- seq2seq/do_small_run.sh
- seq2seq/run_seq2seq_flax.py
Trying to make bart-large work
> fix: model config + save optim

- demo/dalle_mini
- requirements.txt
Also, change model configuration to `bart-large-cnn`.
Does not appear to have much impact.
> Score results using pre-trained CLIP.

- app/app_gradio.py
- requirements.txt
requirements.txt for app (including streamlit for now) moved to root as requested by Boris
> add gradio demo

- app/app.py
this adds improvement for the sidebar of the app
> app sidebar + improvements

- app/app.py
* "Project Report".
* Prevent empty search when `Again` is tapped after manually emptying the input text field.
> Demo improvements

- app/app.py
As proposed by @khalidsaifullaah. I think it does look a bit better.
> Center sidebar description

- dalle_mini/text.py
This PR adds `dalle_mini.text.TextNormalizer` for cleaning up the text
> feat: add text utilities

- dalle_mini/text.py
- dev/inference/samples.txt
- dev/inference/wandb-backend.ipynb
- feat: update wandb inference
- feat: add more samples
> feat: update wandb inference

- dalle_mini/text.py
- feat(text): use hf_hub for wiki word count
- feat(text): few improvements
> feat: improve text processing

- dalle_mini/model.py
- dev/inference/samples.txt
- dev/seq2seq/run_seq2seq_flax.py
- setup.cfg
Several improvements:
- use model definition
- correct use of dtype
- add more metrics
- use custom TrainingArguments
- cleanup
fixes #106
> feat: refactor seq2seq script

- dev/seq2seq/run_seq2seq_flax.py
- feat: use pretrained weights
- feat: avoid OOM
> feat: use pretrained weights

- dalle_mini/data.py
- dev/seq2seq/run_seq2seq_flax.py
Data loading is now handled in separate file.
This will make it easier to support webdataset.
> feat: handle data in separate file

- src/dalle_mini/data.py
- tools/inference/inference_pipeline.ipynb
- tools/train/train.py
- feat: refactor training arguments
- fix: handle seed_dataset
> feat(train): refactor arguments

- src/dalle_mini/model/__init__.py
- src/dalle_mini/model/configuration.py
- src/dalle_mini/model/modeling.py
- src/dalle_mini/model/tokenizer.py
- src/dalle_mini/model/wandb_pretrained.py
- tools/train/train.py
> Load from wandb

- src/dalle_mini/data.py
- src/dalle_mini/model/__init__.py
- src/dalle_mini/model/modeling.py
- tools/train/train.py
Use pjit to allow Model + Data Parallelism
Fixes #124
> feat(train): use pjit

- tools/train/scalable_shampoo/distributed_shampoo.py
- tools/train/scalable_shampoo/symmetric_matrices/symmetric_matrices.py
- tools/train/train.py
log norm and histograms of parameters and gradients﻿
> feat(train): log norm and histograms

- src/dalle_mini/model/text.py
> text is utf8 encoded so we need to read it as such

- README.md
- src/dalle_mini/model/configuration.py
- src/dalle_mini/model/modeling.py
Implement [Sinkformers: Transformers with Doubly Stochastic Attention](https://arxiv.org/abs/2110.11773)
> feat: add sinkformer + custom final ln + pre-ln

- src/dalle_mini/model/modeling.py
> feat: sinkhorn in lse mode

- setup.cfg
- src/dalle_mini/model/text.py
Allow emojis.
Merge once variants tests are done.
> feat(text): support emojis

- app/streamlit/app.py
- app/streamlit/backend.py
Backend now returns the model version with the predictions.
> Half the number of requests.

- tools/train/train.py
Learning rate can be offset so it stays at 0 for a custom number of steps
> feat: support LR offset

- README.md
> docs: add dalle flow project to readme

- Docker/Dockerfile
- run_docker_image.sh
- tools/inference/run_infer_notebook.sh
This PR adds the ability to use the inference notebook inside of the docker container
> feat: made changes to improve usage of Docker and infer notebook

- run_docker_image.sh
You can delete the first line of code by directly setting the PDW command in Docker run :)
> right annotation of "PWD"

- run_docker_image.sh
By my fault, I canceled the previous pull request.
> setting the container name again

- README.md
Small readability changes in the readme.md file
> doc(README): fix typos

- tools/train/embeddings_retrain_preparation.ipynb
> Notebook to initialize embeddings for retraining

- tools/train/train.py
We may not need this anymore, but it could still be handy.
This change allows us to load a pre-trained model and reinitialize the embedding layers before training, instead of using a separate notebook to create and upload a prepared model.
> When training embeddings, optionally init them.

- app/gradio/app.py
- setup.cfg
- src/dalle_mini/model/modeling.py
- tools/inference/inference_pipeline.ipynb
- tools/train/train.py
> style: lint
